# Generated by Django 3.1.3 on 2020-12-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201217_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='social_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
