# Generated by Django 3.1.4 on 2021-04-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210411_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
