# Generated by Django 3.1.4 on 2021-04-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_student_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='updated_at',
        ),
    ]
